# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-CCfLpYS9g1rkGM4nZ1Xcu3d1MvSzJi
"""

import pandas as pd

df = pd.read_csv("marketing_campaign.csv", sep="\t")

df['Income'].fillna(df['Income'].median(), inplace=True)

df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True)

df['Education'] = df['Education'].str.strip().str.lower()
df['Marital_Status'] = df['Marital_Status'].str.strip().str.lower()

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.drop_duplicates(inplace=True)

df['year_birth'] = df['year_birth'].astype(int)
df['recency'] = df['recency'].astype(int)

df.to_csv("cleaned_marketing_campaign.csv", index=False)

print("✅ Dataset cleaned and saved as 'cleaned_marketing_campaign.csv'")